### PR TITLE
possible fix for issue #3

### PR DESCRIPTION
**Pull request by jtokarchuk**
took some inspiration from the way DNSChef does things.

Implements:
- SocketServer
- s.recv instead of recvfrom

Seems to be running stable on windows, however do not have a Linux or mac box to test on.

### CODE REVIEW

**Comment by jtokarchuk** [comment]
issue #3

**Comment by jtokarchuk** [comment]
howdy, I really appreciated your help yesterday, so I dug in to look for a fix.

go open source!

**Comment by Crypt0s** [comment]
Thanks for contributing!!

**Comment by jtokarchuk** [comment]
changes seem sensible to me, tested on windows for the last 30 minutes without a crash (where it would crash inside of 5 minutes before)

and yeah, I agree, windows is stupid.

**Comment by Crypt0s** [comment]
Merged with changes made.  Closing.

**Pull request merged**
