### PR TITLE
Port option

### PR DESCRIPTION
**Pull request by Linuturk**
Adds an option to change the default port FakeDns listens on.

```
usage: fakedns.py [-h] -c PATH [-i IFACE] [-p PORT] [--rebind]

things and stuff

optional arguments:
  -h, --help  show this help message and exit
  -c PATH     Path to configuration file
  -i IFACE    IP address you wish to run FakeDns with - default all
  -p PORT     Port number you wish to run FakeDns
  --rebind    Enable DNS rebinding attacks - responds with one result the
              first request, and another result on subsequent requests
```

### CODE REVIEW

**Comment by Crypt0s** [comment]
Hey thanks for the pull request.  I just have to find some time to test this before merging it but it seems like a good idea.

**Comment by Linuturk** [comment]
For what it is worth, I did test this locally. Successfully launched and queried the service on a port other than 53.

**Comment by Crypt0s** [comment]
Sorry I've been unresponsive.  Right now I'm Working on a rewrite to the code to improve readability, performance, and add DNS round robin, will be adding these feature in and giving you some credit, as well as adding the whitelist examples

**Comment by Linuturk** [comment]
Sounds good. :+1:

**Comment by Crypt0s** [comment]
Hey was about to merge this but it looks like the whitelist is actually a blacklist? Seems like the entries would be black-holing those two domains to the requestors localhost if they were to evaluate to true.  Can you confirm?

**Comment by Linuturk** [comment]
That uses regex to do a negative lookahead. It effectively directs all requests to the localhost addresses except for requests containing the strings defined. It certainly isn't as clean as it could be if proper whitelisting was implemented, but I didn't want to make any big modifications to the scripts logic. This uses regex to hack around the limitation.

**Comment by Crypt0s** [comment]
Awesome, I'll add this as an example of whitelisting until I (or someone else) implements DNS whitelisting.

**Pull request merged**
