### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by allanlewis**
This branch makes the code largely compliant with PEP 8, PEP 257 and Pylint.

Warning: This is completely untested.

### CODE REVIEW

**Comment by Crypt0s** [comment]
Thank you for the pull request! I've seen this pull request and will test it "soon" when I get a moment :)

**Comment by allanlewis** [comment]
:+1:

**Comment by Crypt0s** [comment]
I tested it *a little* and it didn't blow anything up.  Approved.
Thanks for contributing!

**Comment by allanlewis** [comment]
Thanks, @Crypt0s!

**Pull request merged**
